version: '3.2'
networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rememberer
      MYSQL_USER: rememberer
      MYSQL_PASSWORD: rememberer
    ports: ['33060:3306']
    networks:
      - backend-network